# Generated by Django 4.0.10 on 2024-08-17 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storeAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
